/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Character: typeof import('./components/character/index.vue')['default']
    CircleComponent: typeof import('./components/draw/circle-component.vue')['default']
    EditHeader: typeof import('./components/edit-header/index.vue')['default']
    Header: typeof import('./components/header/index.vue')['default']
    InputBox: typeof import('./components/input/input-box.vue')['default']
    Login: typeof import('./components/login/index.vue')['default']
    MessageList: typeof import('./components/message/message-list.vue')['default']
    MessageSelectTipsPopup: typeof import('./components/message/message-selectTips-popup.vue')['default']
    NavBar: typeof import('./components/nav-bar/index.vue')['default']
    Popup: typeof import('./components/popup.vue')['default']
    PullList: typeof import('./components/pullList.vue')['default']
    ReminderSet: typeof import('./components/reminderSet.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Schedule: typeof import('./components/schedule/index.vue')['default']
    SelectSex: typeof import('./components/selectSex/index.vue')['default']
    UniRecord: typeof import('./components/record/uni-record.vue')['default']
    WeekPanel: typeof import('./components/schedule/weekPanel.vue')['default']
    WybNoticeBar: typeof import('./components/wyb-noticeBar/wyb-noticeBar.vue')['default']
  }
}
